development:
  # calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH # deepak
  # calendly_key: CDCKABHIPEI24LNXS7QPVNT53BB2B6QS # sumit
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4 # kristi
  # calendly_key: PGPDHFGNNOFZQGJQZ37C4K7UBWMO5VE7 # deepak yuvasoft
  server_url: https://d560a2fb.ngrok.io
  mailgun:
    key: key-26b3924502603002f75c25ebde19be8e
    domain: mg.coral.media

production:
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4 # kristi
  # calendly_key: PGPDHFGNNOFZQGJQZ37C4K7UBWMO5VE7 # deepak yuvasoft
  server_url: https://calendly-demo.herokuapp.com
  mailgun:
    key: key-26b3924502603002f75c25ebde19be8e
    domain: mg.coral.media
