development:
  # calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH # deepak
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: http://9c67fe28.ngrok.io

production:
  # calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH # deepak
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://calendly-demo.herokuapp.com