development:
  calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH
  # calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://8a01e68a.ngrok.io

production:
  calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH
  # calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://calendly-demo.herokuapp.com