development:
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://8a01e68a.ngrok.io

production:
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://calendly-demo.herokuapp.com