development:
  # calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH # deepak
  # calendly_key: CDCKABHIPEI24LNXS7QPVNT53BB2B6QS # sumit
  calendly_key: PGPDHFGNNOFZQGJQZ37C4K7UBWMO5VE7 # deepak yuvasoft
  # calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4 #kristi
  server_url: https://236d543c.ngrok.io

production:
  # calendly_key: HIJKENJOGHBR2DN4S7YD57DUD2PQIPSH # deepak
  calendly_key: EFHFAGHAJCKYVGHQDLAMG364BNBY2RQ4
  server_url: https://calendly-demo.herokuapp.com
